credentials:
  usernames:
    admin:
      email: admin@iotracx.com
      name: Admin
      password: $2b$12$7HvQ3UScGrB4VkcqOjnMcOXv9q09vnCvCblB.zMaXqjI7krX13Yh2
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - preetham.trh@gmail.com
  - siddharthabhat09@gmail.com